stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/training.1600000.processed.noemoticon.csv
    outs:
    - data/X_test.csv:
        persist: true
    - data/X_train.csv:
        persist: true
    - data/y_test.csv:
        persist: true
    - data/y_train.csv:
        persist: true
    frozen: true

  raw_to_txt:
    cmd: python src/raw_to_txt.py
    deps:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv
    - params.yaml
    frozen: true

  keras_embedding:
    cmd: python src/keras_embedding.py --action nature

    metrics:
    - metrics/embedding/embedding_metrics_nature.json
    outs:
      - confusion_matrices/Confusion_matrix_embeddings_nature.jpg:
          persist: true
    plots:
    - logs_nature_dvc_plots/binary_accuracy.json:
        cache: false
        x: step
        y: acc
    - logs_nature_dvc_plots/auc.json:
        cache: false
        x: step
        y: auc
    - logs_nature_dvc_plots/cost_metric.json:
        cache: false
        x: step
        y: cost_metric
    - logs_nature_dvc_plots/loss.json:
        cache: false
        x: step
        y: loss
    - logs_nature_dvc_plots/precision.json:
        cache: false
        x: step
        y: precision
    - logs_nature_dvc_plots/precision_at_recall.json:
        cache: false
        x: step
        y: precision_at_recall
    - logs_nature_dvc_plots/recall.json:
        cache: false
        x: step
        y: recall
    - logs_nature_dvc_plots/sensitivity_at_specificity.json:
        cache: false
        x: step
        y: sensitivity_at_specificity
    - logs_nature_dvc_plots/specificity_at_sensitivity.json:
        cache: false
        x: step
        y: specificity_at_sensitivity
    - logs_nature_dvc_plots/val_binary_accuracy.json:
        cache: false
        x: step
        y: val_acc
    - logs_nature_dvc_plots/val_auc.json:
        cache: false
        x: step
        y: val_auc
    - logs_nature_dvc_plots/val_cost_metric.json:
        cache: false
        x: step
        y: val_cost_metric
    - logs_nature_dvc_plots/val_loss.json:
        cache: false
        x: step
        y: val_loss
    - logs_nature_dvc_plots/val_precision.json:
        cache: false
        x: step
        y: val_precision
    - logs_nature_dvc_plots/val_precision_at_recall.json:
        cache: false
        x: step
        y: val_precision_at_recall
    - logs_nature_dvc_plots/val_recall.json:
        cache: false
        x: step
        y: val_recall
    - logs_nature_dvc_plots/val_sensitivity_at_specificity.json:
        cache: false
        x: step
        y: val_sensitivity_at_specificity
    - logs_nature_dvc_plots/val_specificity_at_sensitivity.json:
        cache: false
        x: step
        y: val_specificity_at_sensitivity


