prepare:
  train_size: 100000
  test_size: 20000

keras:
  recall: 0.5
  specificity: 0.5
  sensitivity: 0.5

model_constants:
  max_features: 100000
  embedding_dim: 300
  sequence_length: 30
  maxlen: 30
  training_samples: 80000
  validation_samples: 20000
  max_words: 100000
  unit_cost_of_a_bad_buzz: 250
  optimizer: rmsprop
  fasttext_300: word2vec/wiki-news-300d-1M.vec

keras_embedding:
  batch_size: 256
  epochs: 25
  dense: 128

keras_glove:
  embedding_dim: 100
  epochs: 25
  dense: 32

keras_lstm:
  epochs: 25
  dense: 32

keras_w2v:
  epochs: 25
  optimizer: rmsprop
  dense: 32

keras_bert:
  batch_size: 32
  epochs: 25
  dense: 32
